name: runner test
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: [self-hosted, Windows, X64]
        # container:
        #     image: ghcr.io/kasperfiskerdk/msbuilddockerimage:0.2

        steps:
            - name: Checking out branch from project hello
              uses: actions/checkout@v4

            - name: Pulling docker image
              run: docker pull ghcr.io/kasperfiskerdk/win64_msvc2022:0.2

            - name: Build hello in docker image
              run: docker run -v .:C:\project win64_msvc2022:0.2 ./build_hello.bat
