name: runner test
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: [self-hosted, Windows, X64]

        # On windows the following to lines specifying which image the runner should use, is not supported?!!
        # container:
        #     image: ghcr.io/kasperfiskerdk/msbuilddockerimage:0.2

        steps:
            - name: Checking out branch from project hello
              uses: actions/checkout@v4

            - name: Pulling windows-with-build-tools docker image and build hello
              run: docker run --pull missing -v .:C:\project ghcr.io/kasperfiskerdk/win64_msvc2022:0.2 ./build_hello.bat

